services:
- type: pserv
  repo: https://github.com/1liale/debatemodai
  rootDir: backend
  name: debate-mod-agent
  runtime: docker
  plan: starter
  numInstances: 2

  envVars:
  - fromGroup: debate-mod-env

  region: virginia
  maxShutdownDelaySeconds: 300

version: "1" 