services:
- type: pserv
  repo: https://github.com/1liale/debatemodai
  rootDir: backend
  name: debate-mod-agent
  runtime: docker
  plan: starter

  envVars:
  - fromGroup: debate-mod-env

  region: virginia
  maxShutdownDelaySeconds: 300

  scaling:
    minInstances: 1
    maxInstances: 4
    targetCPUPercent: 60
    targetMemoryPercent: 60

version: "1" 